swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /admision/:
    get:
      tags:
      - admision
      description: get Admision
      operationId: AdmisionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Admision'
        "403":
          description: ""
    post:
      tags:
      - admision
      description: create Admision
      operationId: AdmisionController.Post
      parameters:
      - in: body
        name: body
        description: body for Admision content
        required: true
        schema:
          $ref: '#/definitions/models.Admision'
      responses:
        "201":
          description: '{int} models.Admision'
        "403":
          description: body is empty
  /admision/{id}:
    get:
      tags:
      - admision
      description: get Admision by id
      operationId: AdmisionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Admision'
        "403":
          description: :id is empty
    put:
      tags:
      - admision
      description: update the Admision
      operationId: AdmisionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Admision content
        required: true
        schema:
          $ref: '#/definitions/models.Admision'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Admision'
        "403":
          description: :id is not int
    delete:
      tags:
      - admision
      description: delete the Admision
      operationId: AdmisionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /estado_admision/:
    get:
      tags:
      - estado_admision
      description: get EstadoAdmision
      operationId: EstadoAdmisionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.EstadoAdmision'
        "403":
          description: ""
    post:
      tags:
      - estado_admision
      description: create EstadoAdmision
      operationId: EstadoAdmisionController.Post
      parameters:
      - in: body
        name: body
        description: body for EstadoAdmision content
        required: true
        schema:
          $ref: '#/definitions/models.EstadoAdmision'
      responses:
        "201":
          description: '{int} models.EstadoAdmision'
        "403":
          description: body is empty
  /estado_admision/{id}:
    get:
      tags:
      - estado_admision
      description: get EstadoAdmision by id
      operationId: EstadoAdmisionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.EstadoAdmision'
        "403":
          description: :id is empty
    put:
      tags:
      - estado_admision
      description: update the EstadoAdmision
      operationId: EstadoAdmisionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for EstadoAdmision content
        required: true
        schema:
          $ref: '#/definitions/models.EstadoAdmision'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.EstadoAdmision'
        "403":
          description: :id is not int
    delete:
      tags:
      - estado_admision
      description: delete the EstadoAdmision
      operationId: EstadoAdmisionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /linea_investigacion/:
    get:
      tags:
      - linea_investigacion
      description: get LineaInvestigacion
      operationId: LineaInvestigacionController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.LineaInvestigacion'
        "403":
          description: ""
    post:
      tags:
      - linea_investigacion
      description: create LineaInvestigacion
      operationId: LineaInvestigacionController.Post
      parameters:
      - in: body
        name: body
        description: body for LineaInvestigacion content
        required: true
        schema:
          $ref: '#/definitions/models.LineaInvestigacion'
      responses:
        "201":
          description: '{int} models.LineaInvestigacion'
        "403":
          description: body is empty
  /linea_investigacion/{id}:
    get:
      tags:
      - linea_investigacion
      description: get LineaInvestigacion by id
      operationId: LineaInvestigacionController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.LineaInvestigacion'
        "403":
          description: :id is empty
    put:
      tags:
      - linea_investigacion
      description: update the LineaInvestigacion
      operationId: LineaInvestigacionController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for LineaInvestigacion content
        required: true
        schema:
          $ref: '#/definitions/models.LineaInvestigacion'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.LineaInvestigacion'
        "403":
          description: :id is not int
    delete:
      tags:
      - linea_investigacion
      description: delete the LineaInvestigacion
      operationId: LineaInvestigacionController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Admision:
    title: Admision
    type: object
    properties:
      Aspirante:
        type: integer
        format: int64
      Enfasis:
        type: integer
        format: int64
      EstadoAdmision:
        $ref: '#/definitions/models.EstadoAdmision'
      Id:
        type: integer
        format: int64
      LineaInvestigacion:
        $ref: '#/definitions/models.LineaInvestigacion'
      Periodo:
        type: integer
        format: int64
      ProgramaAcademico:
        type: integer
        format: int64
      Propuesta:
        type: integer
        format: int64
      ReciboInscripcion:
        type: integer
        format: int64
      ReciboMatricula:
        type: integer
        format: int64
  models.EstadoAdmision:
    title: EstadoAdmision
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.LineaInvestigacion:
    title: LineaInvestigacion
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      GrupoInvestigacion:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: admision
  description: |
    AdmisionController operations for Admision
- name: estado_admision
  description: |
    EstadoAdmisionController operations for EstadoAdmision
- name: linea_investigacion
  description: |
    LineaInvestigacionController operations for LineaInvestigacion
